name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read  # least-privilege

jobs:
  pre-commit:
    name: Run pre-commit (fail on diffs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Runs hooks; if any hook reformats/fixes files, the job will fail
      # (no commits/pushes attempted).
      - name: Run pre-commit (all files)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
