name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write      # allow pushing fixes to the PR branch
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit env
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit (and auto-fix if needed)
        id: run
        shell: bash
        run: |
          set -e
          FIX=0
          pre-commit run --all-files || FIX=1
          if [ "$FIX" = "1" ]; then
            echo "pre-commit made changes; committing..."
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(pre-commit): auto-fixes" || true
            git push
          fi
